---
contentdir: "content"
layoutdir: "layouts"
publishdir: "./../public"
indexes:
  category: "categories"
baseurl: "https://www.bajoneando.com/"
theme: hugo-cactus-theme
title: "Bajoneando Blog"
canonifyurls: true
googleAnalytics: UA-81286834-1


params:
  name: "Luis Ramirez Monterosa"
  description: "Bajoneando Blog"
  twitter: luisnramirez
  iconFont: mono-social
  bio: "Cyclist - Coffee Enthusiast - Functional Student"

social:
    twitter: https://www.twitter.com/luisnramirez
    github: https://github.com/lnramirez
